package io.github.p4suta.walaru.model;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/** Public, compiler-independent JSR-45 mapper shared by Walaru JVM consumers. */
public final class KotlinSourceMap {
    private final String sourcePath;
    private final List<Entry> entries;

    private KotlinSourceMap(String sourcePath, List<Entry> entries) {
        this.sourcePath = sourcePath;
        this.entries = entries;
    }

    /** Parses the Kotlin stratum and safely preserves bytecode positions for unknown forms. */
    public static KotlinSourceMap parse(String debug, String defaultSource) {
        String fallback = defaultSource == null ? "Unknown.java" : defaultSource;
        if (debug == null || !debug.startsWith("SMAP")) return new KotlinSourceMap(fallback, List.of());
        String[] lines = debug.split("\\R");
        Map<Integer, String> files = new LinkedHashMap<>();
        List<Entry> mappings = new ArrayList<>();
        // The third SMAP header line declares the default stratum. Some Kotlin compilers omit an
        // explicit `*S Kotlin` section and start directly with `*F`/`*L`.
        boolean kotlinStratum = lines.length > 2 && lines[2].trim().equals("Kotlin");
        boolean fileSection = false;
        boolean lineSection = false;
        for (int index = 0; index < lines.length; index++) {
            String line = lines[index].trim();
            if (line.startsWith("*S ")) {
                if (kotlinStratum && !mappings.isEmpty()) break;
                kotlinStratum = line.equals("*S Kotlin");
                fileSection = false;
                lineSection = false;
                continue;
            }
            if (!kotlinStratum) continue;
            if (line.equals("*F")) {
                fileSection = true;
                lineSection = false;
                continue;
            }
            if (line.equals("*L")) {
                fileSection = false;
                lineSection = true;
                continue;
            }
            if (line.startsWith("*")) {
                fileSection = false;
                lineSection = false;
                continue;
            }
            if (fileSection) {
                try {
                    if (line.startsWith("+ ")) {
                        String[] fields = line.substring(2).trim().split("\\s+", 2);
                        int id = Integer.parseInt(fields[0]);
                        String path = index + 1 < lines.length ? lines[++index].trim() : fields[1];
                        files.put(id, path);
                    } else if (!line.isEmpty()) {
                        String[] fields = line.split("\\s+", 2);
                        files.put(Integer.parseInt(fields[0]), fields.length == 2 ? fields[1] : fallback);
                    }
                } catch (RuntimeException ignored) {
                    // Vendor additions do not invalidate the remainder of the mapping.
                }
                continue;
            }
            if (lineSection && line.contains(":")) {
                parseLine(line, files, fallback).ifPresent(mappings::add);
            }
        }
        String primary = files.getOrDefault(1, files.values().stream().findFirst().orElse(fallback));
        return new KotlinSourceMap(primary, List.copyOf(mappings));
    }

    /** Returns the logical Kotlin path and line for one generated bytecode line. */
    public Position position(int outputLine) {
        for (Entry entry : entries) {
            int end = entry.outputStart + (entry.repeat - 1) * entry.outputIncrement;
            if (outputLine >= entry.outputStart && outputLine <= end) {
                return new Position(
                        entry.path,
                        entry.inputStart + (outputLine - entry.outputStart) / entry.outputIncrement);
            }
        }
        return new Position(sourcePath, outputLine);
    }

    /** Primary source path declared by the Kotlin stratum. */
    public String sourcePath() {
        return sourcePath;
    }

    private static Optional<Entry> parseLine(String line, Map<Integer, String> files, String fallback) {
        try {
            String[] sides = line.split(":", 2);
            String input = sides[0];
            int fileId = 1;
            int hash = input.indexOf('#');
            if (hash >= 0) {
                int end = input.indexOf(',', hash);
                fileId = Integer.parseInt(input.substring(hash + 1, end < 0 ? input.length() : end));
                input = input.substring(0, hash) + (end < 0 ? "" : input.substring(end));
            }
            String[] inputParts = input.split(",", 2);
            String[] outputParts = sides[1].split(",", 2);
            return Optional.of(new Entry(
                    Integer.parseInt(inputParts[0]),
                    Integer.parseInt(outputParts[0]),
                    inputParts.length == 2 ? Integer.parseInt(inputParts[1]) : 1,
                    outputParts.length == 2 ? Integer.parseInt(outputParts[1]) : 1,
                    files.getOrDefault(fileId, fallback)));
        } catch (RuntimeException ignored) {
            return Optional.empty();
        }
    }

    /** Immutable logical source position. */
    public record Position(String path, int line) {}

    private record Entry(int inputStart, int outputStart, int repeat, int outputIncrement, String path) {}
}
